/* =========================================================
   SPELLING BEE — VOCABULARY LIST
   -----------------------------------------------------------
   Real vocabulary + audio recorded with ElevenLabs.
   Each entry:
     word:  the correct English spelling
     audio: filename inside assets/audio/
   ========================================================= */
const SPELLING_WORDS = [
  { word: "Portuguese", audio: "portuguese.mp3" },
  { word: "English", audio: "english.mp3" },
  { word: "Maths", audio: "maths.mp3" },
  { word: "Science", audio: "science.mp3" },
  { word: "Arts", audio: "arts.mp3" },
  { word: "Physical Education", audio: "physical-education.mp3" },
  { word: "alligator", audio: "alligator.mp3" },
  { word: "giraffe", audio: "giraffe.mp3" },
  { word: "hippo", audio: "hippo.mp3" },
  { word: "iguana", audio: "iguana.mp3" },
  { word: "leopard", audio: "leopard.mp3" },
  { word: "lion", audio: "lion.mp3" },
  { word: "monkey", audio: "monkey.mp3" },
  { word: "panda", audio: "panda.mp3" },
  { word: "snake", audio: "snake.mp3" },
  { word: "head", audio: "head.mp3" },
  { word: "eye", audio: "eye.mp3" },
  { word: "ear", audio: "ear.mp3" },
  { word: "small nose", audio: "small-nose.mp3" },
  { word: "big mouth", audio: "big-mouth.mp3" },
  { word: "tooth", audio: "tooth.mp3" },
  { word: "sharp teeth", audio: "sharp-teeth.mp3" },
  { word: "long neck", audio: "long-neck.mp3" },
  { word: "short leg", audio: "short-leg.mp3" },
  { word: "tail", audio: "tail.mp3" },
  { word: "tall", audio: "tall.mp3" },
  { word: "Brazil", audio: "brazil.mp3" },
  { word: "Canada", audio: "canada.mp3" },
  { word: "Italy", audio: "italy.mp3" },
  { word: "Japan", audio: "japan.mp3" },
  { word: "Mexico", audio: "mexico.mp3" },
  { word: "The United Kingdom", audio: "the-united-kingdom.mp3" },
  { word: "The United States", audio: "the-united-states.mp3" },
  { word: "computer", audio: "computer.mp3" },
  { word: "headphones", audio: "headphones.mp3" },
  { word: "handbag", audio: "handbag.mp3" },
  { word: "trousers", audio: "trousers.mp3" },
  { word: "roller skates", audio: "roller-skates.mp3" },
  { word: "towel", audio: "towel.mp3" },
  { word: "Mike's jacket", audio: "mikes-jacket.mp3" },
  { word: "Calvin's glasses", audio: "calvins-glasses.mp3" },
  { word: "What have you got?", audio: "what-have-you-got.mp3" },
  { word: "I've got stickers.", audio: "ive-got-stickers.mp3" },
  { word: "I love animals!", audio: "i-love-animals.mp3" },
  { word: "I like cats!", audio: "i-like-cats.mp3" },
  { word: "I don't like monsters!", audio: "i-dont-like-monsters.mp3" },
  { word: "Where are you from?", audio: "where-are-you-from.mp3" },
  { word: "I'm from Brazil.", audio: "im-from-brazil.mp3" },
  { word: "She's a teacher.", audio: "shes-a-teacher.mp3" },
  { word: "He's my friend.", audio: "hes-my-friend.mp3" },
];
